<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Air Conditioners
            [
                'brand_id' => 1, // Samsung
                'sku' => 'SAM-AC-AR5500-1.5T',
                'name' => 'Samsung WindFree AR5500 1.5 Ton Inverter AC',
                'slug' => 'samsung-windfree-ar5500-15-ton-inverter-ac',
                'description' => 'Experience comfortable cooling without direct wind. WindFree™ technology disperses air through 23,000 micro air holes. Digital Inverter technology maintains desired temperature with less fluctuation.',
                'short_description' => '1.5 Ton 5 Star Inverter Split AC with WindFree cooling',
                'model_number' => 'AR18CYECAWKNNA',
                'power_consumption' => '1440W',
                'voltage' => '230V',
                'frequency' => '50Hz',
                'energy_rating' => '5 Star',
                'dimensions' => '1055 x 299 x 215 mm',
                'weight' => 11.5,
                'color' => 'White',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 45999.00,
                'compare_price' => 55999.00,
                'cost' => 35000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 11, // Daikin
                'sku' => 'DAI-AC-FTKM50-1.5T',
                'name' => 'Daikin 1.5 Ton 3 Star Inverter Split AC',
                'slug' => 'daikin-15-ton-3-star-inverter-split-ac',
                'description' => 'Daikin\'s inverter technology with power chill operation and Coanda airflow. Stabilizer free operation and copper condenser for better cooling.',
                'short_description' => '1.5 Ton 3 Star Inverter AC with Copper Condenser',
                'model_number' => 'FTKM50TV',
                'power_consumption' => '1480W',
                'voltage' => '230V',
                'frequency' => '50Hz',
                'energy_rating' => '3 Star',
                'dimensions' => '1050 x 298 x 212 mm',
                'weight' => 11.0,
                'color' => 'White',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 36999.00,
                'compare_price' => 42999.00,
                'cost' => 28000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Washing Machines
            [
                'brand_id' => 2, // LG
                'sku' => 'LG-WM-FHM1408-8KG',
                'name' => 'LG 8 Kg Front Load Washing Machine with AI Direct Drive',
                'slug' => 'lg-8kg-front-load-washing-machine-ai-direct-drive',
                'description' => 'AI Direct Drive™ technology detects fabric texture and load to automatically set the optimum washing pattern. 6 Motion DD technology provides optimized motion combinations for each fabric type.',
                'short_description' => '8 Kg Fully Automatic Front Load with Steam Wash',
                'model_number' => 'FHM1408BDL',
                'power_consumption' => '2100W',
                'voltage' => '220-240V',
                'frequency' => '50Hz',
                'energy_rating' => '5 Star',
                'dimensions' => '600 x 560 x 850 mm',
                'weight' => 62.0,
                'color' => 'Black Steel',
                'material' => 'Stainless Steel Drum',
                'country_of_origin' => 'India',
                'price' => 38999.00,
                'compare_price' => 46999.00,
                'cost' => 30000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1, // Samsung
                'sku' => 'SAM-WM-WW70T4020-7KG',
                'name' => 'Samsung 7 Kg Top Load Washing Machine',
                'slug' => 'samsung-7kg-top-load-washing-machine',
                'description' => 'Wobble technology provides gentle care of fabrics without compromising washing performance. Diamond Drum is designed to be gentle on your clothes.',
                'short_description' => '7 Kg Fully Automatic Top Load Washing Machine',
                'model_number' => 'WW70T4020EE',
                'power_consumption' => '340W',
                'voltage' => '220-240V',
                'frequency' => '50Hz',
                'energy_rating' => '5 Star',
                'dimensions' => '540 x 550 x 925 mm',
                'weight' => 32.0,
                'color' => 'Imperial Silver',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 22999.00,
                'compare_price' => 26999.00,
                'cost' => 35000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Refrigerators
            [
                'brand_id' => 1, // Samsung
                'sku' => 'SAM-REF-RT28T-253L',
                'name' => 'Samsung 253L Double Door Refrigerator',
                'slug' => 'samsung-253l-double-door-refrigerator',
                'description' => 'Digital Inverter Compressor automatically adjusts its speed in response to cooling demand. All Round Cooling ensures optimal temperature throughout.',
                'short_description' => '253L Frost Free Double Door Refrigerator',
                'model_number' => 'RT28T3483S8',
                'power_consumption' => '195W',
                'voltage' => '220-240V',
                'frequency' => '50Hz',
                'energy_rating' => '3 Star',
                'dimensions' => '555 x 637 x 1545 mm',
                'weight' => 54.0,
                'color' => 'Elegant Inox',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 25999.00,
                'compare_price' => 29999.00,
                'cost' => 20000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2, // LG
                'sku' => 'LG-REF-GLS322-308L',
                'name' => 'LG 308L Smart Inverter Double Door Refrigerator',
                'slug' => 'lg-308l-smart-inverter-double-door-refrigerator',
                'description' => 'Smart Inverter Compressor provides unmatched performance, great savings and super silent operation. Multi Air Flow ensures ideal temperature levels throughout.',
                'short_description' => '308L Frost Free Refrigerator with Smart Diagnosis',
                'model_number' => 'GL-S322SPZY',
                'power_consumption' => '205W',
                'voltage' => '220-240V',
                'frequency' => '50Hz',
                'energy_rating' => '3 Star',
                'dimensions' => '585 x 670 x 1640 mm',
                'weight' => 62.0,
                'color' => 'Shiny Steel',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 32999.00,
                'compare_price' => 38999.00,
                'cost' => 35000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // TVs
            [
                'brand_id' => 3, // Sony
                'sku' => 'SONY-TV-A80J-55',
                'name' => 'Sony BRAVIA 55 inch 4K OLED Smart TV',
                'slug' => 'sony-bravia-55-inch-4k-oled-smart-tv',
                'description' => 'Cognitive Processor XR™ understands how humans see and hear to deliver intense contrast with pure blacks. XR OLED Contrast Pro boosts color and contrast.',
                'short_description' => '55" 4K HDR OLED TV with Cognitive Processor XR',
                'model_number' => 'XR-55A80J',
                'power_consumption' => '352W',
                'voltage' => '110-240V',
                'frequency' => '50/60Hz',
                'energy_rating' => 'A+',
                'dimensions' => '1227 x 712 x 53 mm',
                'weight' => 18.7,
                'color' => 'Black',
                'material' => 'Premium Metal',
                'country_of_origin' => 'Malaysia',
                'price' => 129999.00,
                'compare_price' => 159999.00,
                'cost' => 95000.00,
                'tax_rate' => 28.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 1, // Samsung
                'sku' => 'SAM-TV-QN90A-65',
                'name' => 'Samsung 65 inch Neo QLED 4K Smart TV',
                'slug' => 'samsung-65-inch-neo-qled-4k-smart-tv',
                'description' => 'Quantum Matrix Technology precisely controls our exclusive new Quantum Mini LEDs. Neural Quantum Processor 4K upgrades every picture to 4K with AI.',
                'short_description' => '65" Neo QLED 4K HDR Smart TV',
                'model_number' => 'QA65QN90AAKXXL',
                'power_consumption' => '235W',
                'voltage' => '100-240V',
                'frequency' => '50/60Hz',
                'energy_rating' => 'A',
                'dimensions' => '1446.6 x 829.3 x 25.7 mm',
                'weight' => 25.5,
                'color' => 'Titan Black',
                'material' => 'ABS Plastic',
                'country_of_origin' => 'India',
                'price' => 189999.00,
                'compare_price' => 224999.00,
                'cost' => 35000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vacuum Cleaners
            [
                'brand_id' => 7, // Dyson
                'sku' => 'DYS-V15-DETECT',
                'name' => 'Dyson V15 Detect Absolute Cordless Vacuum',
                'slug' => 'dyson-v15-detect-absolute-cordless-vacuum',
                'description' => 'Reveals invisible dust with laser. Scientific proof of a deep clean with piezo sensor. 60 minutes of fade-free power. HEPA filtration.',
                'short_description' => 'Most powerful cordless vacuum with laser dust detection',
                'model_number' => 'V15 Detect',
                'power_consumption' => '660W',
                'voltage' => '25.2V',
                'frequency' => 'N/A',
                'energy_rating' => 'A+++',
                'dimensions' => '1264 x 251 x 266 mm',
                'weight' => 3.1,
                'color' => 'Yellow/Nickel',
                'material' => 'Advanced Polymers',
                'country_of_origin' => 'Malaysia',
                'price' => 52999.00,
                'compare_price' => 62900.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Microwave Ovens
            [
                'brand_id' => 1, // Samsung
                'sku' => 'SAM-MW-MC28H-28L',
                'name' => 'Samsung 28L Convection Microwave Oven',
                'slug' => 'samsung-28l-convection-microwave-oven',
                'description' => 'HotBlast™ technology significantly reduces cooking times. Slim Fry™ technology for healthier fried food. Ceramic enamel interior.',
                'short_description' => '28L Convection Microwave with Slim Fry Technology',
                'model_number' => 'MC28H5015VK',
                'power_consumption' => '2900W',
                'voltage' => '230V',
                'frequency' => '50Hz',
                'energy_rating' => '3 Star',
                'dimensions' => '517 x 476 x 310 mm',
                'weight' => 17.0,
                'color' => 'Black',
                'material' => 'Advanced Polymers',
                'country_of_origin' => 'Malaysia',
                'price' => 12999.00,
                'compare_price' => 15999.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Coffee Makers
            [
                'brand_id' => 5, // Philips
                'sku' => 'PHI-EP3241-74',
                'name' => 'Philips 3200 Series Fully Automatic Espresso Machine',
                'slug' => 'philips-3200-series-automatic-espresso-machine',
                'description' => 'Enjoy 5 coffee varieties at your fingertips. LatteGo milk system for silky smooth milk froth. Intuitive touch display.',
                'short_description' => 'Fully Automatic Espresso Machine with LatteGo',
                'model_number' => 'EP3241/74',
                'power_consumption' => '1500W',
                'voltage' => '230V',
                'frequency' => '50Hz',
                'energy_rating' => 'A',
                'dimensions' => '246 x 371 x 433 mm',
                'weight' => 8.0,
                'color' => 'Piano Black',
                'material' => 'Plastic/Stainless Steel',
                'country_of_origin' => 'Romania',
                'price' => 49999.00,
                'compare_price' => 59999.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hair Dryers
            [
                'brand_id' => 7, // Dyson
                'sku' => 'DYS-HD07-SUPERSONIC',
                'name' => 'Dyson Supersonic Hair Dryer',
                'slug' => 'dyson-supersonic-hair-dryer',
                'description' => 'Intelligent heat control to protect shine. Air Multiplier™ technology for fast drying. Magnetic attachments for easy adjustment.',
                'short_description' => 'Professional hair dryer with intelligent heat control',
                'model_number' => 'HD07',
                'power_consumption' => '1600W',
                'voltage' => '220-240V',
                'frequency' => '50/60Hz',
                'energy_rating' => 'A',
                'dimensions' => '245 x 78 x 97 mm',
                'weight' => 0.66,
                'color' => 'Iron/Fuchsia',
                'material' => 'Advanced Polymers',
                'country_of_origin' => 'Malaysia',
                'price' => 27999.00,
                'compare_price' => 33000.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Air Purifiers
            [
                'brand_id' => 7, // Dyson
                'sku' => 'DYS-TP07-PURE-COOL',
                'name' => 'Dyson Pure Cool™ TP07 Air Purifier',
                'slug' => 'dyson-pure-cool-tp07-air-purifier',
                'description' => 'Automatically senses and captures pollutants. HEPA H13 filter captures 99.95% of particles. Air Multiplier™ technology.',
                'short_description' => 'HEPA Air Purifier and Tower Fan',
                'model_number' => 'TP07',
                'power_consumption' => '40W',
                'voltage' => '220-240V',
                'frequency' => '50/60Hz',
                'energy_rating' => 'A+',
                'dimensions' => '1050 x 220 x 220 mm',
                'weight' => 4.6,
                'color' => 'White/Silver',
                'material' => 'Advanced Polymers',
                'country_of_origin' => 'Malaysia',
                'price' => 44999.00,
                'compare_price' => 54900.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Electric Kettles
            [
                'brand_id' => 5, // Philips
                'sku' => 'PHI-HD9306-1.5L',
                'name' => 'Philips Daily Collection Electric Kettle',
                'slug' => 'philips-daily-collection-electric-kettle',
                'description' => '1.5L capacity with 1800W for fast boiling. Triple safety system with auto shut-off.',
                'short_description' => '1.5L Electric Kettle with Concealed Element',
                'model_number' => 'HD9306/06',
                'power_consumption' => '1800W',
                'voltage' => '220-240V',
                'frequency' => '50/60Hz',
                'energy_rating' => 'A+',
                'dimensions' => '223 x 157 x 250 mm',
                'weight' => 1.0,
                'color' => 'White/Blue',
                'material' => 'Advanced Polymers',
                'country_of_origin' => 'Malaysia',
                'price' => 1999.00,
                'compare_price' => 2495.00,
                'cost' => 40000.00,
                'tax_rate' => 18.00,
                'is_featured' => true,
                'is_active' => true,
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);

        $this->command->info('Products table seeded successfully!');
    }
}
